import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from utils.decay_math import convert_to_ci, UNITS
from utils.constants import (
    CI_TO_MBQ, GAMMA_DOSE_CONSTANT, NEUTRON_SOURCES, DOSE_LIMITS, GAMMA_HVL,
    gamma_dr_from_activity, neutron_dr_from_activity,
)

st.set_page_config(page_title="Shielding Calculator", page_icon="🛡️", layout="wide")

GAMMA_MATERIALS = ['Lead', 'Steel', 'Concrete', 'Water']
GAMMA_DENSITY   = {'Lead': 11.35, 'Steel': 7.87, 'Concrete': 2.30, 'Water': 1.00}
GAMMA_COLOR     = {'Lead': '#455A64', 'Steel': '#1565C0', 'Concrete': '#E64A19', 'Water': '#0288D1'}

# ── Neutron shielding (relaxation length λ, cm) ───────────────────────────────
# Sources: IAEA TECDOC, Profio "Radiation Shielding and Dosimetry"
NEUTRON_RELAX    = {
    'Am-Be':  {'HDPE': 8.3, 'Concrete': 13.0, 'Water': 9.5,  'Paraffin': 8.0},
    'Cf-252': {'HDPE': 7.5, 'Concrete': 11.5, 'Water': 8.5,  'Paraffin': 7.3},
}
NEUTRON_MATERIALS = ['HDPE', 'Concrete', 'Water', 'Paraffin']
NEUTRON_DENSITY   = {'HDPE': 0.95, 'Concrete': 2.30, 'Water': 1.00, 'Paraffin': 0.90}
NEUTRON_COLOR     = {'HDPE': '#2E7D32', 'Concrete': '#E64A19', 'Water': '#0288D1', 'Paraffin': '#F57C00'}

# ── PHITS source energies ──────────────────────────────────────────────────────
PHITS_SRC = {
    'Am-241': {'proj': 'photon',  'e0': 0.0595, 'note': '59.5 keV gamma'},
    'Ba-133': {'proj': 'photon',  'e0': 0.356,  'note': 'dominant 356 keV gamma'},
    'Co-60':  {'proj': 'photon',  'e0': 1.252,  'note': 'average of 1173 + 1332 keV lines'},
    'Cs-137': {'proj': 'photon',  'e0': 0.662,  'note': '662 keV gamma'},
    'Eu-152': {'proj': 'photon',  'e0': 0.344,  'note': 'dominant 344 keV gamma'},
    'Ge-68':  {'proj': 'photon',  'e0': 0.511,  'note': '511 keV annihilation gamma'},
    'Ir-192': {'proj': 'photon',  'e0': 0.380,  'note': 'effective average ~380 keV'},
    'Mn-54':  {'proj': 'photon',  'e0': 0.835,  'note': '835 keV gamma'},
    'Na-22':  {'proj': 'photon',  'e0': 0.511,  'note': '511 keV annihilation gamma'},
    'Pu-239': {'proj': 'photon',  'e0': 0.414,  'note': 'dominant 414 keV gamma'},
    'Ra-226': {'proj': 'photon',  'e0': 0.609,  'note': 'Bi-214 609 keV dominant line'},
    'Y-88':   {'proj': 'photon',  'e0': 0.898,  'note': 'dominant 898 keV gamma'},
    'Am-Be':  {'proj': 'neutron', 'e0': 4.5,    'note': 'mean neutron energy ~4.5 MeV (mono approx.)'},
    'Cf-252': {'proj': 'neutron', 'e0': 2.35,   'note': 'mean Watt spectrum energy ~2.35 MeV (mono approx.)'},
}

# Material compositions for PHITS (weight fractions, negative = wt%)
PHITS_MAT = {
    'Lead':     {'density': 11.35, 'comp': '   Pb  1.0',
                 'comment': 'Lead (Pb)'},
    'Steel':    {'density':  7.87, 'comp': '   Fe  1.0',
                 'comment': 'Steel (simplified as pure Fe)'},
    'Concrete': {'density':  2.30, 'comp': (
                 '   H  -0.0100\n   C  -0.0010\n   O  -0.5295\n'
                 '   Na -0.0160\n   Mg -0.0020\n   Al -0.0335\n'
                 '   Si -0.3370\n   K  -0.0130\n   Ca -0.0440\n   Fe -0.0140'),
                 'comment': 'Ordinary concrete (NIST composition, wt fractions)'},
    'Water':    {'density':  1.00, 'comp': '   H  2.0\n   O  1.0',
                 'comment': 'Water (H2O)'},
    'HDPE':     {'density':  0.95, 'comp': '   H  2.0\n   C  1.0',
                 'comment': 'High-density polyethylene (CH2)n'},
    'Paraffin': {'density':  0.90, 'comp': '   H  2.0\n   C  1.0',
                 'comment': 'Paraffin wax (approx. CH2)'},
}


# ── Physics ────────────────────────────────────────────────────────────────────
def gamma_thickness_cm(dr_i, dr_t, hvl):
    return hvl * np.log2(dr_i / dr_t) if dr_i > dr_t else 0.0

def neutron_thickness_cm(dr_i, dr_t, lam):
    return lam * np.log(dr_i / dr_t) if dr_i > dr_t else 0.0

def gamma_dr(dr_i, t, hvl):
    return dr_i * 0.5 ** (t / hvl)

def neutron_dr_atten(dr_i, t, lam):
    return dr_i * np.exp(-t / lam)


# ── PHITS input file generator ─────────────────────────────────────────────────
def generate_phits_inp(src_key, mat_key, thickness_cm, ref_dist_cm, maxcas, maxbch):
    src  = PHITS_SRC[src_key]
    mat  = PHITS_MAT[mat_key]
    proj = src['proj']
    e0   = src['e0']
    buf  = 50.0
    z1   = ref_dist_cm
    z2   = ref_dist_cm + thickness_cm
    z3   = z2 + 200.0
    z4   = z3 + 50.0

    dmax = f" dmax(2)  =  {max(e0*2, 20.0):.1f}         $ max neutron data energy [MeV]\n" if proj == "neutron" else ""
    parts = "neutron photon" if proj == "neutron" else "photon"
    fname = f"dose_z_{src_key.replace('-','').replace(' ','_')}_{mat_key}"

    return (
f"""[ T i t l e ]
Shielding simulation: {src_key} source, {mat_key} shield ({thickness_cm:.1f} cm)
Generated by Nuclear Source Toolkit (Radiation Safety Officer tool)

$ Output: EPS file generated by ANGEL post-processor (epsout = 1).
$         Open with SumatraPDF (requires Ghostscript installed) or
$         convert to PDF via ANGEL bundled with PHITS.

[ P a r a m e t e r s ]
 icntl    =         0     $ (D=0) normal calculation run
 maxcas   = {maxcas:>9d}     $ particles per batch
 maxbch   = {maxbch:>9d}     $ number of batches
 emin(12) =     0.001     $ min photon transport energy [MeV]
{dmax}
[ S o u r c e ]
  totfact =   1.0         $ source strength [particles/s]
                          $ Set to actual emission rate for absolute dose rates.
                          $ Example: 1 MBq {src_key} ≈ {_totfact_hint(src_key)} photons(neutrons)/s
   s-type =   1           $ mono-energetic point source
     proj =   {proj:<10}  $ particle type
       e0 =   {e0:.4f}       $ source energy [MeV]  ({src['note']})
       r0 =   0.0         $ point source (r0 = 0)
       x0 =   0.0
       y0 =   0.0
       z0 =   0.0
       z1 =   0.0
      dir =  -1.0         $ isotropic emission

[ M a t e r i a l ]
MAT[ 1 ]  $ Air (dry, near sea level, ρ = 0.001205 g/cm³)
    N  -0.7553
    O  -0.2318
    Ar -0.0128
    C  -0.0001

MAT[ 2 ]  $ {mat['comment']} (ρ = {mat['density']} g/cm³)
{mat['comp']}

[ S u r f a c e ]
   10  pz  {-buf:.1f}        $ bottom boundary (buffer below source)
   11  pz  {z1:.2f}       $ shield front face  (reference distance = {ref_dist_cm:.1f} cm)
   12  pz  {z2:.2f}       $ shield back face   (shield thickness   = {thickness_cm:.1f} cm)
   13  pz  {z3:.2f}     $ detector region back boundary
   14  pz  {z4:.2f}     $ outer top boundary
   20  cz  300.0            $ outer cylindrical boundary (radius = 300 cm)

[ C e l l ]
   1    1 -0.001205    10 -11 -20   $ Air: source region to shield front
   2    2 -{mat['density']:.4f}      11 -12 -20   $ Shield: {mat_key}
   3    1 -0.001205    12 -13 -20   $ Air: detector region (behind shield)
   4    1 -0.001205    13 -14 -20   $ Air: outer region
  99   -1              (-10 : 14 : 20)  $ Outer void

[ T - T r a c k ]
    title = Effective dose rate: {src_key} → {mat_key} ({thickness_cm:.1f} cm)
     mesh =  xyz
   x-type =    2
     xmin =   -5.0
     xmax =    5.0
       nx =    1
   y-type =    2
     ymin =   -5.0
     ymax =    5.0
       ny =    1
   z-type =    2
     zmin =   {-buf:.1f}
     zmax =   {z3:.1f}
       nz =   200
   e-type =    1
       ne =    1
            1.00000E-10  1.00000E+03
     unit =    1           $ [1/cm²/source particle]
 material =  all
  2D-type =    3           $ color mesh output
     axis =    z
     file =  {fname}.out
     part =  {parts}
 multiplier = all
     emax =  1000.0
  mat mset1
    all  ( 3600*1e-6 -202 )  $ [pSv/source] × 3600e-6 → [μSv/h / (particle/s)]  (ICRP 103)
    gshow =    1           $ show geometry boundaries on plot
    resol =    1
    width =    0.5
   epsout =    1           $ generate EPS file via ANGEL (open with SumatraPDF + Ghostscript)

[ E n d ]
""")


def _totfact_hint(src_key):
    hints = {
        'Am-241': '3.6×10⁵  (35.9% gamma yield × 1×10⁶ Bq)',
        'Cs-137': '8.5×10⁵  (85.1% gamma yield × 1×10⁶ Bq)',
        'Co-60':  '2.0×10⁶  (~200% gamma yield × 1×10⁶ Bq)',
        'Ir-192': '8.2×10⁵  (82% gamma yield × 1×10⁶ Bq)',
        'Am-Be':  '6.5×10⁴  (65 n/s per MBq Am-241)',
        'Cf-252': '1.17×10⁸ (116600 n/s per MBq Cf-252)',
    }
    return hints.get(src_key, 'see isotope decay data')


# ── Page ───────────────────────────────────────────────────────────────────────
st.title("🛡️ Shielding Calculator")
st.markdown(
    "Calculate required shielding thickness using **Half-Value Layer (HVL)** for gamma "
    "and **relaxation length (λ)** for neutron sources, per ICRP 103 dose limits."
)

with st.sidebar:
    st.header("⚙️ Settings")
    st.subheader("📋 Dose limits (reference)")
    st.caption("ICRP 103 / IAEA BSS — assuming 2000 working h/yr")
    for lbl, d in DOSE_LIMITS.items():
        st.metric(lbl, f"{d['uSvh']} μSv/h")
    st.divider()
    st.caption(
        "**Method:** Broad-beam HVL (gamma) / exponential relaxation length (neutron). "
        "No scatter, skyshine, or room-return correction. "
        "For complex geometry use Monte Carlo (PHITS / MCNP)."
    )

# ── Source type ────────────────────────────────────────────────────────────────
st.markdown("### Source type")
source_type = st.radio("Source type", ["Gamma", "Neutron"], horizontal=True,
                        label_visibility="collapsed")
st.divider()

if source_type == "Gamma":
    st.markdown("### Isotope")
    isotope_sel = st.selectbox("Isotope", list(GAMMA_HVL.keys()),
                                label_visibility="collapsed")
    hvl_data    = GAMMA_HVL[isotope_sel]
    src_name    = isotope_sel

    st.markdown(f"**Dominant gamma energy:** {hvl_data['dominant_keV']} keV")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Lead HVL",     f"{hvl_data['Lead']} cm")
    c2.metric("Steel HVL",    f"{hvl_data['Steel']} cm")
    c3.metric("Concrete HVL", f"{hvl_data['Concrete']} cm")
    c4.metric("Water HVL",    f"{hvl_data['Water']} cm")
    materials   = GAMMA_MATERIALS
    mat_density = GAMMA_DENSITY
    mat_colors  = GAMMA_COLOR
else:
    st.markdown("### Neutron source type")
    source_sel = st.selectbox("Neutron source type", list(NEUTRON_RELAX.keys()),
                               label_visibility="collapsed")
    relax_data = NEUTRON_RELAX[source_sel]
    ns         = NEUTRON_SOURCES[source_sel]
    src_name   = source_sel

    st.markdown(f"**Relaxation lengths (λ) for fast-neutron dose attenuation:**")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("HDPE λ",     f"{relax_data['HDPE']} cm")
    c2.metric("Concrete λ", f"{relax_data['Concrete']} cm")
    c3.metric("Water λ",    f"{relax_data['Water']} cm")
    c4.metric("Paraffin λ", f"{relax_data['Paraffin']} cm")
    materials   = NEUTRON_MATERIALS
    mat_density = NEUTRON_DENSITY
    mat_colors  = NEUTRON_COLOR

st.divider()

# ── Dose rate inputs ───────────────────────────────────────────────────────────
col_dr, col_target = st.columns(2, gap="large")

with col_dr:
    st.subheader("Unshielded dose rate")
    dr_mode = st.radio("Specify as", ["Calculate from activity", "Enter directly"],
                        horizontal=True)

    if dr_mode == "Calculate from activity":
        act_unit = st.selectbox("Activity unit", UNITS, key="shield_act_unit")
        act_val  = st.number_input("Activity", min_value=0.0, value=1.0,
                                    format="%.6f", key="shield_act_val")
        dist_m   = st.number_input("Distance from source (m)", min_value=0.01,
                                    value=1.0, format="%.2f", key="shield_dist")

        act_MBq = convert_to_ci(act_val, act_unit) * CI_TO_MBQ
        if source_type == "Gamma":
            dr_initial = gamma_dr_from_activity(act_MBq, GAMMA_DOSE_CONSTANT[isotope_sel], dist_m)
        else:
            nr = neutron_dr_from_activity(act_MBq, ns['neutron_yield_per_MBq'],
                                           ns['h_phi_pSv_cm2'], dist_m)
            gr = gamma_dr_from_activity(act_MBq, ns['gamma_dose_constant'], dist_m) \
                 if ns['gamma_dose_constant'] > 0 else 0.0
            dr_initial = nr + gr

        st.metric("Calculated dose rate", f"{dr_initial:.4f} μSv/h")
    else:
        dr_initial = st.number_input(
            "Dose rate without shielding (μSv/h)",
            min_value=0.001, value=100.0, format="%.3f",
            help="Measured or calculated dose rate at your reference point before shielding."
        )

with col_target:
    st.subheader("Target dose rate")
    target_mode = st.radio("Set target as", ["ICRP 103 limit", "Custom value"], horizontal=True)
    if target_mode == "ICRP 103 limit":
        limit_sel = st.selectbox("Dose limit", list(DOSE_LIMITS.keys()))
        dr_target = DOSE_LIMITS[limit_sel]['uSvh']
        st.caption(f"Target: **{dr_target} μSv/h**")
    else:
        dr_target = st.number_input("Custom target (μSv/h)",
                                     min_value=0.001, value=0.5, format="%.3f")

if dr_initial > dr_target:
    rf = dr_initial / dr_target
    st.markdown(
        f"**Required attenuation: {rf:.1f}×  |  "
        f"Reduction: {(1 - 1/rf)*100:.1f}%  |  "
        f"Equivalent to {np.log2(rf):.1f} HVLs (gamma) / {np.log(rf):.1f} relaxation lengths (neutron)**"
    )

st.divider()

# ── Results ────────────────────────────────────────────────────────────────────
if dr_initial <= dr_target:
    st.success(
        f"No shielding required — current dose rate ({dr_initial:.3f} μSv/h) "
        f"is already at or below the target ({dr_target} μSv/h)."
    )
    st.stop()

st.subheader("Required shielding thickness")

rows = []
if source_type == "Gamma":
    for mat in GAMMA_MATERIALS:
        hvl = hvl_data[mat]
        t   = gamma_thickness_cm(dr_initial, dr_target, hvl)
        rows.append({'Material': mat, 'Density (g/cm³)': GAMMA_DENSITY[mat],
                     'HVL (cm)': hvl, 'Required (cm)': round(t, 2),
                     'Required (mm)': round(t * 10, 1),
                     'Areal density (g/cm²)': round(t * GAMMA_DENSITY[mat], 1)})
else:
    for mat in NEUTRON_MATERIALS:
        lam = relax_data[mat]
        t   = neutron_thickness_cm(dr_initial, dr_target, lam)
        rows.append({'Material': mat, 'Density (g/cm³)': NEUTRON_DENSITY[mat],
                     'Relaxation length λ (cm)': lam, 'Required (cm)': round(t, 2),
                     'Required (mm)': round(t * 10, 1),
                     'Areal density (g/cm²)': round(t * NEUTRON_DENSITY[mat], 1)})

df_results = pd.DataFrame(rows)
st.dataframe(df_results, use_container_width=True, hide_index=True)

if source_type == "Neutron" and source_sel == "Am-Be":
    st.info(
        "**Am-Be combined shielding recommendation:**  \n"
        "Am-Be emits both **fast neutrons** (table above) and **59.5 keV gamma rays** from "
        "the Am-241 matrix. A typical layered shield uses:  \n"
        "1. **Inner lead layer** (~0.5–1 cm) — attenuates Am-241 gamma  \n"
        "2. **Outer HDPE / paraffin layer** (~20–30 cm) — moderates and absorbs fast neutrons  \n\n"
        "Switch to the **Gamma** tab and select **Am-241** to calculate the lead thickness.",
        icon="⚠️"
    )

# ── Comparison bar chart ───────────────────────────────────────────────────────
st.subheader("Material comparison")
fig_bar = go.Figure(go.Bar(
    x=df_results['Material'],
    y=df_results['Required (cm)'],
    marker_color=[mat_colors[m] for m in df_results['Material']],
    text=[f"{t} cm" for t in df_results['Required (cm)']],
    textposition='outside', width=0.5,
))
fig_bar.update_layout(
    title=f"Required thickness — {src_name}  ({dr_initial:.2f} → {dr_target:.2f} μSv/h)",
    yaxis_title="Required thickness (cm)",
    yaxis=dict(rangemode='tozero'),
    showlegend=False, template="plotly_white",
)
st.plotly_chart(fig_bar, use_container_width=True)

# ── Transmission curve ─────────────────────────────────────────────────────────
st.subheader("Dose rate vs shield thickness")

max_t  = max(r['Required (cm)'] for r in rows)
x_arr  = np.linspace(0, max_t * 1.6 + 2, 400)

# Clamp y-axis so Am-241/Lead doesn't collapse the scale to 10^-300
y_min_plot = max(dr_target * 0.001, 1e-9)
y_max_plot = dr_initial * 2.0

fig_tx = go.Figure()
for row in rows:
    mat = row['Material']
    if source_type == "Gamma":
        y = np.maximum([gamma_dr(dr_initial, x, row['HVL (cm)']) for x in x_arr], y_min_plot)
    else:
        y = np.maximum([neutron_dr_atten(dr_initial, x, row['Relaxation length λ (cm)'])
                        for x in x_arr], y_min_plot)
    fig_tx.add_trace(go.Scatter(
        x=x_arr, y=y, mode='lines', name=mat,
        line=dict(color=mat_colors[mat], width=2.5),
    ))

for lbl, d in DOSE_LIMITS.items():
    fig_tx.add_hline(y=d['uSvh'], line_dash='dash', line_color=d['color'],
                      annotation_text=lbl, annotation_position='bottom right')

fig_tx.update_layout(
    title=f"Dose rate attenuation — {src_name}",
    xaxis_title="Shield thickness (cm)",
    yaxis_title="Dose rate (μSv/h)",
    yaxis_type="log",
    yaxis_range=[np.log10(y_min_plot), np.log10(y_max_plot)],
    template="plotly_white",
    hovermode="x unified",
    legend=dict(orientation="h", y=-0.25, font=dict(size=13)),
)
st.plotly_chart(fig_tx, use_container_width=True)

# ── PHITS input file generator ─────────────────────────────────────────────────
with st.expander("⚙️ Generate PHITS simulation input file (.inp)", expanded=False):
    st.markdown(
        "Generate a ready-to-run PHITS input file for a point-source slab shielding geometry. "
        "The tally outputs effective dose rate (μSv/h per source particle/s) along the z-axis "
        "using ICRP 103 fluence-to-dose conversion. "
        "**epsout = 1** produces an EPS file viewable in SumatraPDF (with Ghostscript installed)."
    )
    st.divider()

    p1, p2 = st.columns(2)
    with p1:
        phits_mat   = st.selectbox(
            "Shield material for PHITS",
            [m for m in (GAMMA_MATERIALS if source_type == "Gamma" else NEUTRON_MATERIALS)
             if m in PHITS_MAT],
        )
        phits_t     = st.number_input("Shield thickness to simulate (cm)",
                                       min_value=0.1, value=float(round(max_t, 1)) if max_t > 0 else 10.0,
                                       format="%.1f")
        phits_dist  = st.number_input("Source-to-shield distance (cm)",
                                       min_value=1.0, value=100.0, format="%.1f")
    with p2:
        phits_cas   = st.number_input("Particles per batch (maxcas)", min_value=1000,
                                       value=100000, step=10000)
        phits_bch   = st.number_input("Number of batches (maxbch)", min_value=1,
                                       value=10, step=1)

    if st.button("Generate .inp file", type="primary"):
        inp_content = generate_phits_inp(
            src_key=src_name, mat_key=phits_mat,
            thickness_cm=phits_t, ref_dist_cm=phits_dist,
            maxcas=int(phits_cas), maxbch=int(phits_bch),
        )
        fname = f"shield_{src_name.replace('-','').replace(' ','_')}_{phits_mat}_{phits_t:.0f}cm.inp"
        st.download_button("⬇️ Download .inp file", inp_content, fname, "text/plain",
                            key="phits_dl")
        st.code(inp_content, language="text")

# ── Download results ───────────────────────────────────────────────────────────
st.divider()
st.download_button(
    "⬇️ Download shielding results (CSV)",
    df_results.to_csv(index=False),
    f"shielding_{src_name}_{dr_initial:.1f}to{dr_target:.1f}uSvh.csv",
    "text/csv",
)
